package noc

type FlitState string

const (
	FLIT_STATE_UNKNOWN = FlitState("UNKNOWN")

	FLIT_STATE_INPUT_BUFFER = FlitState("INPUT_BUFFER")

	FLIT_STATE_ROUTE_COMPUTATION = FlitState("ROUTE_COMPUTATION")

	FLIT_STATE_VIRTUAL_CHANNEL_ALLOCATION = FlitState("VIRTUAL_CHANNEL_ALLOCATION")

	FLIT_STATE_SWITCH_ALLOCATION = FlitState("SWITCH_ALLOCATION")

	FLIT_STATE_SWITCH_TRAVERSAL = FlitState("SWITCH_TRAVERSAL")

	FLIT_STATE_LINK_TRAVERSAL = FlitState("LINK_TRAVERSAL")

	FLIT_STATE_DESTINATION_ARRIVED = FlitState("DESTINATION_ARRIVED")
)

var VALID_FLIT_STATES = []FlitState{
	FLIT_STATE_INPUT_BUFFER,
	FLIT_STATE_ROUTE_COMPUTATION,
	FLIT_STATE_VIRTUAL_CHANNEL_ALLOCATION,
	FLIT_STATE_SWITCH_ALLOCATION,
	FLIT_STATE_SWITCH_TRAVERSAL,
	FLIT_STATE_LINK_TRAVERSAL,
	FLIT_STATE_DESTINATION_ARRIVED,
}
